name: Sync Data on PR Merge and Push to Main

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run npm script
        run: npm run sync-data
